### ISSUE TITLE
Add force_method

### ISSUE THREAD

**Issue by shaninalex** [shaninalex/oauthkeeper-custom-authenticators#1]
Use only GET http method for verifying authorization ( documentation: https://www.ory.sh/docs/oathkeeper/pipeline/authn#bearer_token-configuration )

Example:
```
authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  bearer_token:
    enabled: true
    config:
      check_session_url: http://authorizer:8003/verify
      preserve_path: true
      preserve_query: true
      force_method: GET  # <---- add
      extra_from: "@this"
      subject_from: "@this.Subject"
      token_from:
        header: Authorization
      forward_http_headers:
        - Authorization
  noop:
    enabled: true
```

In other case it will forward http method also, but custom authrizer accept only GET
